image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build project
    init: mvn -f ecomarkets -fn install
    command: mvn -f ecomarkets -DskipTests quarkus:dev

ports:
  - port: 9000
    onOpen: ignore
    visibility: public
  - port: 9090
    onOpen: ignore
    visibility: public
  - port: 3336
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - esbenp.prettier-vscode
    - svelte.svelte-vscode