image:
  file: .gitpod.Dockerfile

tasks:
  - name: API
    init: mvn -f ecomarkets -fn install
    command: mvn -f ecomarkets -DskipTests quarkus:dev

  - name: APP
    init: |
      cd ecomarkets-app
      npm install
      npm run build
    command: |
      cd ecomarkets-app
      npm run dev

ports:
    # APP
  - port: 5173
    onOpen: ignore
    visibility: public
    # API
  - port: 9090
    onOpen: ignore
    visibility: public
    # DB
  - port: 3336
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - esbenp.prettier-vscode
    - svelte.svelte-vscode
    - ms-vscode.vscode-typescript-next
