image:
  file: .gitpod.Dockerfile

tasks:
  - name: CORE
    init: mvn -fn -DskipTests install
    command: |
      cd core
      quarkus dev

  - name: WEB
    command: |
      sleep 10
      cd web
      quarkus dev

  - name: API
    command: |
      sleep 15
      cd api 
      quarkus dev

  - name: VDN
    command: |
      sleep 20
      cd vdn
      quarkus dev

  - name: SKN
    init: |
      cd ecomarkets-app
      npm install
      npm run build
    command: |
      sleep 25
      cd ecomarkets-app
      npm run dev

  - name: PROXY
    command: |
      sleep 30
      docker compose up
  
  - name: SHELL
    command: |
      echo "Hello from the shell"

ports:
    # APP
  - port: 5173
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore
    visibility: public
    # API
  - port: 9090
    onOpen: ignore
    visibility: public

  - port: 5005
    onOpen: ignore
    visibility: private
    # DB
  - port: 3336
    onOpen: ignore
    visibility: public
    # PROXY
  - port: 6600
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - esbenp.prettier-vscode
    - svelte.svelte-vscode
    - ms-vscode.vscode-typescript-next

additionalRepositories:
  - url: https://github.com/CaravanaCloud/ecomarkets-secrets
