# docker compose -f docker-compose.nginx.yaml down; docker compose -f docker-compose.nginx.yaml up; 
services:

  nginx:
    image: nginx
    container_name: nginx
    network_mode: host
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999

