receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: otel-collector:4317
      http: 
        endpoint: otel-collector:4318
  otlp/2:
    protocols:
      grpc:
        endpoint: otel-collector:55680


exporters:
  logging:
    loglevel: debug

  prometheus:
    endpoint: otel-collector:8889
    namespace: default

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto


processors:
  batch: 
  
extensions:
  health_check: # http://localhost:13133
  # fetches the collector’s performance data
  pprof: # http://localhost:1777
  # serves as an http endpoint that provides live debugging data about instrumented components.


service:
  extensions: [health_check, pprof]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    traces:
      receivers: [otlp, otlp/2]
      processors: [batch]
      exporters: [zipkin,logging]
    logs:
      receivers: [otlp]
      exporters: [logging]
      