AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EcoMarkets Lambda Module

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:
  EcoMarketsWebBucket:
    Type: AWS::S3::Bucket

  EcoMarketsApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java21
      CodeUri: target/function.zip
      MemorySize: 256
      Timeout: 30
      Policies: AWSLambdaBasicExecutionRole
 #     Env:
 #       WebBucketName: !Ref EcoMarketsWebBucket
      Events:
        HttpApiEvent:
          Type: HttpApi

Outputs:
  LambdademoApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: LambdademoApi