# sam deploy --stack-name cfn-db --template-file infra_db.cfn.yaml --resolve-s3

AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template: Aurora  MySQL Database'
Parameters:
  ParamsStackName:
    Description: The name of the params stack
    Type: String
    Default: 'cfn-params'
  NetworkStackName:
    Description: The name of the network stack
    Type: String
    Default: 'cfn-net'
  AllowCIDR:
    Description: The CIDR block for the security group
    Type: String
    Default: '0.0.0.0/0'
  AllocatedStorage:
    Description: AllocatedStorage
    Type: Number
    Default: 5
  DBClusterInstanceClass:
    Description: InstanceClass
    Type: String
    Default: 'db.t4g.micro'
  PubliclyAccessible:
    Description: PubliclyAccessible
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
  DBName:
    Type: String
    Default: "ecomarkets"

Resources:
  CfnDbSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for Aurora MySQL Database'
      VpcId: 
        Fn::ImportValue:
          !Sub '${NetworkStackName}-VPCId'

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref AllowCIDR

  CfnDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'Subnet group for Aurora Serverless DB cluster'
      SubnetIds: 
        - Fn::ImportValue:
            !Sub '${NetworkStackName}-PublicSubnet1Id'
        - Fn::ImportValue:
            !Sub '${NetworkStackName}-PublicSubnet2Id'
        - Fn::ImportValue:
            !Sub '${NetworkStackName}-PublicSubnet3Id'
  
  CfnDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: 'mysql'
      EngineVersion: '8.0'
      MasterUsername: !Sub '{{resolve:ssm:${ParamsStackName}-DBUsername}}'
      MasterUserPassword: !Sub '{{resolve:ssm:${ParamsStackName}-DBPassword}}'
      VPCSecurityGroups: 
        - !GetAtt  CfnDbSecurityGroup.GroupId
      DBSubnetGroupName: !Ref CfnDBSubnetGroup
      PubliclyAccessible: !Ref PubliclyAccessible
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: !Ref DBClusterInstanceClass
      DBName: DBName

Outputs:
  DBInstanceIdentifier:
    Description: The identifier of the DB instance
    Value: !Ref CfnDBInstance
  DBInstanceEndpoint:
    Description: The connection endpoint for the DB instance
    Value: !GetAtt CfnDBInstance.Endpoint.Address
  DBInstancePort:
    Description: The port number on which the DB instance accepts connections
    Value: !GetAtt CfnDBInstance.Endpoint.Port
  DBInstanceSecurityGroup:
    Description: The security group of the DB instance
    Value: !GetAtt CfnDbSecurityGroup.GroupId
  JDBCURL:
    Description: JDBC URL
    Value: !Sub "jdbc:mysql://${CfnDBInstance.Endpoint.Address}:${CfnDBInstance.Endpoint.Port}/${DBName}"
    Export:
      Name:  !Sub "${AWS::StackName}-JDBCURL"
