# sam deploy --stack-name cfn-fn --template-file infra_fn.cfn.yaml --resolve-s3 --capabilities "CAPABILITY_IAM" "CAPABILITY_AUTO_EXPAND" 

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"
Parameters:
  DBStackName:
    Description: The name of the params stack
    Type: String
    Default: 'cfn-db'

Resources:
  CfnApiFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java21
      CodeUri: target/function.zip
      MemorySize: 256
      Timeout: 30
      Policies: AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          QUARKUS_PROFILE: "prod"
          QUARKUS_DATASOURCE_JDBC_URL:
            Fn::ImportValue:
              !Sub "${DBStackName}-JDBCURL"
          # TODO AVOID using master for app
          QUARKUS_DATASOURCE_USERNAME:
            !Sub '{{resolve:ssm:${ParamsStackName}-DBUsername}}'
          QUARKUS_DATASOURCE_PASSWORD:
            !Sub '{{resolve:ssm:${ParamsStackName}-DBPassword}}'

      Events:
        HttpApiEvent:
          Type: HttpApi

Outputs:
  CfnApiURL:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: CfnApiURL