apiVersion: v1

baseDomain: $OCP_BASE_DOMAIN
credentialsMode: Manual

metadata:
  name: $CLUSTER_NAME

compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    platform: {}  
    replicas: 0

controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1
  platform: 
    aws:
      type: $INSTANCE_TYPE

platform:
  aws:
    region: $AWS_REGION

publish: External

pullSecret: '$PULL_SECRET'
sshKey: |
  $SSH_KEY
