name: Deploy main branch to dev

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.REDHACKS_PERM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.REDHACKS_PERM_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Check AWS auth
      run: aws sts get-caller-identity

    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto' 
        java-version: '21'
        
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build project
      run: mvn -B -fn --no-transfer-progress install
      working-directory: ecomarkets

    - name: Deploy to AWS 
      working-directory: ecomarkets
      env:
        ENV_ID: "ecotest"
        STACK_NAME: "ecomarkets-dev"
        DomainName: "perm.ecofeiras.com"
        RegionalCertificateArn: "arn:aws:acm:us-east-1:570997277768:certificate/fada378f-7bf1-4d1a-8361-4390f8756d9c"
        HostedZoneId: "Z05338353SJBK366COB82"
      run: |
       sam deploy \
          --template-file "infrastructure.cfn.yaml" \
          --stack-name "$STACK_NAME" \
          --capabilities "CAPABILITY_IAM" "CAPABILITY_AUTO_EXPAND" \
          --resolve-s3 \
          --parameter-overrides "EnvId=$ENV_ID" \
            "DomainName=$DomainName" \
            "RegionalCertificateArn=$RegionalCertificateArn" \
            "HostedZoneId=$HostedZoneId" \
          --disable-rollback

