name: Deploy main branch to dev

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.REDHACKS_TEMP_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.REDHACKS_TEMP_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Check AWS auth
      run: aws sts get-caller-identity

    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build project
      run: mvn -B -fn --no-transfer-progress install
      working-directory: ecomarkets


    - name: Deploy to AWS 
      working-directory: ecomarkets
      run: |
       sam deploy \
          --template-file infrastructure.cfn.yaml \
          --stack-name  ecomarkets-dev \
          --capabilities CAPABILITY_IAM \
          --resolve-s3

