name: End of day

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  end-of-day:
    runs-on: ubuntu-latest

    env:
      ENV_ID: qa
      AWS_REGION: us-east-1

    steps:
    
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.REDHACKS_PERM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.REDHACKS_PERM_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Distribution
      run: ./scripts/build-dist.sh
